version: '3'

services:
  web:
    image: qdp/web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - web-data:/data
    environment:
      - RUST_LOG=trace

volumes:
  web-data:
